### PR TITLE
Switch from matrix to build stages

### PR DESCRIPTION
**Pull request by cotsog**

### CODE REVIEW

**Comment by JamesMessinger** [comment]
Any particular reason for this?  As far as I can tell, it accomplishes the same task, but slower, since each stage runs sequentially

**Comment by cotsog** [comment]
My bad for the first commit.

In the end you need to make sure to override the `node_js` and `os` keys in your `Deploy` stage.

See https://docs.travis-ci.com/user/build-stages/matrix-expansion/.

**Comment by JamesMessinger** [comment]
It's unnecessary to set the `node_js` and `os` keys in the "Deploy" stage because they are automatically inherited from the build matrix.

See https://docs.travis-ci.com/user/build-stages/#build-stages-and-build-matrix-expansion

**Comment by cotsog** [comment]
It seems my assumptions were wrong. I wrongfully thought that you would need to define the os and node_js keys in you deploy stage in order for the resulting job to be recognized as a different stage. However, I did some tests with and without the keys being defined and I could not reproduce your issue. I'm following up with you via e-mail. Thanks!

**Pull request closed without merging**
